"use strict";
let elec1 = new Electrodomestico('rojo', 'A', 50);
console.log(elec1);
//     console.log(`Color: ${elec1.getColor()}`);
//     console.log(`Consumo: ${elec1.getConsumo()}`);
//     console.log(`Peso: ${elec1.getPeso()}`);
//     console.log(`Precio final: ${elec1.getPrecio()}`);
let lav1 = new Lavadora('blanco', 'F', 50);
console.log(lav1);
let lav2 = new Lavadora('blanco', 'F', 50, 50);
console.log(lav2);
let tele1 = new Television('blanco', 'A', 20, 50, false);
console.log(tele1);
let tele2 = new Television('blanco', 'A', 20, 50, true);
console.log(tele2);
